<a href="https://colab.research.google.com/github/TheBigDen/dap-2024/blob/main/les3/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Открыл в файл в Google Colab (используя собственный форк репозитория).
2. Решил задачи.
3. Сохранил результат в репозиторий github в директорию ./les02
4. Создал pull request в репозиторий https://github.com/chebotarevsa/dap-2024
5. Сдал работу в системе "Пегас", в отчете указал ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'1.26.4'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
z = np.random.random((10, 10))
z_min, z_max = z.min(), z.max()
print("Минимум:", z_min, "Максимум:", z_max)

Минимум: 0.013007550876221297 Максимум: 0.9570179768451541


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.random.rand(5, 10)
z -= z.mean(axis=1, keepdims=True)
print(z)

[[-7.38183200e-02  1.04760533e-01  2.99799620e-01  3.60391795e-01
  -2.95063028e-01  3.59592828e-02 -3.20802474e-02 -3.39141326e-01
  -3.99162994e-01  3.38354684e-01]
 [-3.59764676e-01  2.06627257e-01  1.47448094e-01  5.10426869e-01
   1.49512027e-01 -2.86862190e-01 -3.92600669e-01 -2.83169507e-01
  -1.60759116e-02  3.24458707e-01]
 [-1.08115806e-02  8.51922268e-02  2.78642640e-01 -2.95564501e-02
   3.47794276e-04 -1.91847979e-01 -6.23318151e-01  3.33961843e-01
   2.15812480e-01 -5.84228239e-02]
 [-1.65835007e-01  3.52295543e-01 -1.41534836e-01  2.99188216e-01
   4.02106936e-01 -5.47824092e-01  3.99297662e-01  2.74570101e-01
  -3.97759948e-01 -4.74504574e-01]
 [-1.38325938e-02 -4.14970540e-01  2.51609870e-01 -1.40540145e-01
   5.75810388e-02 -1.16348126e-01  3.02346413e-01 -1.58777024e-01
   3.08400283e-01 -7.54691758e-02]]


5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5, 5)
z[[0, 1]] = z[[1, 0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10, 2))
x, y = z[:, 0], z[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("Радиусы:", r)
print("Углы:", theta)

Радиусы: [1.14340839 1.12049994 0.61739933 0.68857522 0.83881645 0.85046531
 0.52203732 0.62615264 0.85552652 0.87309158]
Углы: [0.69317313 0.80837436 0.60671884 0.35583782 0.07312853 0.90068012
 1.49340015 0.20554029 1.06558906 0.40476889]


7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.84078203 0.78670254 0.47328425 0.35490326 0.49346554 0.64314668
 0.64001284 0.15876959 0.         0.31114475]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)
np.add.at(z, i, 1)
print(z)

[3. 3. 1. 2. 2. 5. 3. 4. 3. 4.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1, 2, 3, 4, 5])
nz = np.zeros(len(z) + (len(z) - 1) * 3)
nz[::4] = z
print(nz)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
z = np.random.random(10)
value = 0.5
closest = z[np.abs(z - value).argmin()]
print("Массив:", z)
print("Ближайшее к", value, "значение:", closest)

Массив: [0.89027125 0.88698207 0.52172327 0.64933507 0.79688482 0.00952394
 0.27690202 0.01930094 0.65654416 0.52423625]
Ближайшее к 0.5 значение: 0.5217232733565018


## Вопросы




# Ответы на вопросы

## 1. Какой тип (dtype) будут иметь элементы массива?
```python
import numpy as np

# Типы данных массивов
print(np.array([1, 4, 2, 5, 3]).dtype)  # int64 или int32 (зависит от системы)
print(np.array([1., 4, 2, 5, 3]).dtype)  # float64
print(np.array([1, 4, 2, 5, 3], dtype='float128').dtype)  # float128
print(np.array([1., 4, 2, 5, 3], dtype='complex128').dtype)  # complex128
print(np.array([1, 4, 2, 5, 3], dtype='float64').dtype)  # float64
print(np.array([1, 4, 2, 5, 3], dtype='int64').dtype)  # int64
print(np.array([1, 4, 2, 5, 3], dtype='bool').dtype)  # bool
print(np.array([1, 4, 2, 5, 3], dtype='str').dtype)  # <U1
print(np.array([1, 4, 2, 5, '3']).dtype)  # <U21 (строки)
print(np.array([1, -4, 2, 0, 1j]).dtype)  # complex128


**2**. Что будет выведено в консоль и почему?
- Операции с массивами
```python
print(np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1')  # '41'
print(np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1])  # -4
print(np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1])  # False
print(np.array([1, -4, 2, 0, True], dtype='int64')[-1])  # 1
print(np.array([1, -4, 2, 0, 1j], dtype='str')[-1])  # '1j'
print(np.array([1, 4, 2, 5, '3'])[-1] * 3)  # '333'


**3**. Каков результат операции?

``` python
print(np.ones((3, 5), dtype=float))  # Матрица 3x5 из 1.0
print(np.full((3, 5), 3.14))  # Матрица 3x5 из 3.14
print(np.linspace(0, 1, 5))  # [0. , 0.25, 0.5 , 0.75, 1. ]
print(np.diag((1, 3, 5)))  # Диагональная матрица с диагональю [1, 3, 5]
print(np.random.random((3, 3)))  # Матрица 3x3 со случайными значениями
print(np.eye(3))  # Единичная матрица 3x3
print(np.empty(3))  # Пустой массив из 3 элементов (значения не инициализированы)




**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
print(X[0, 0])  # 3
print(X[-1, -1])  # 7
print(X[0:1, -1])  # [4]
print(X[0:2, -1])  # [4, 8]
print(X[0:2, 0:2])  # [[3, 5], [7, 6]]
print(X[1, 1:3])  # [6, 8]
print(X[1, :])  # [7, 6, 8, 8]
print(X[:, :])  # Весь массив
print(X[::2, ::2])  # [[3, 2], [1, 7]]
print(X[::-1, ::-1])  # Обратный массив
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
print(np.split(grid, [2]))  # Разделение по строкам
print(np.split(grid, [2], axis=1))  # Разделение по столбцам



**6**. В чем различие между операциями?

``` python
print([1, 2, 3] + [3, 2, 1])  # Конкатенация списков: [1, 2, 3, 3, 2, 1]
print(np.array([1, 2, 3]) + np.array([3, 2, 1]))  # Покомпонентное сложение: [4, 4, 4]


**7**. Как в CodeLab измерить время выполнения кода?  
```python
# Используем магическую команду %%time
%%time
result = sum(range(1000000))


**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
              [7, 6, 8, 8],
              [1, 6, 7, 7]])

print(np.sum(X))  # Сумма всех элементов
print(np.sum(X, axis=1))  # Сумма по строкам
print(np.sum(X, axis=0))  # Сумма по столбцам


**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1, 2, 3, 4])

print(X > 3)  # [False False False True]
print(X < 3)  # [ True  True False False]
print(X[X < 3])  # [1 2]
print(X[X > 3])  # [4]
print(X[X != 3])  # [1 2 4]


**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?  

**Преимущества:**
- 1. Быстрее, так как операции выполняются на уровне C (ближе к железу).
- 2. Меньше памяти, поскольку тип элементов массива фиксирован.
- 3. Мощные инструменты для работы с большими данными (трансформации, вычисления, индексация).
